/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BASE;

//import IMPLEMENTATION.divisasLogic;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author VestigiumSenex
 */
public class DivisasBase extends javax.swing.JPanel {
    
    private dataB xbase;
    
    private DefaultComboBoxModel comboModelOr;
    private DefaultComboBoxModel comboModelDes;
    
    private List<infoDivisas> tipos = null;
            
    private Double fondo;
    private Double valbase;
    /**
     * Creates new form DivisasBase
     */
    public DivisasBase() {
        initComponents();                
        this.initset();              
    }
    
    private void initset(){        
        this.xbase = new dataB();
                
        this.tipos = this.xbase.getObjects();
        
        this.comboModelOr = new DefaultComboBoxModel(this.xbase.getNames().toArray());        
        this.comboModelDes = new DefaultComboBoxModel(this.xbase.getNames().toArray());  
        
        this.cborigen.setModel(this.comboModelOr);
        this.cbdest.setModel(this.comboModelDes);        
        
        this.clearVals();        
    }
    
    private void clearVals(){
        
        this.cborigen.setSelectedIndex(-1);
        this.cbdest.setSelectedIndex(-1);
        this.txtDest.setText(null);
        this.txtSource.setText(null);
    }
    
    
    private void translate(){
        
                if(this.cborigen.getSelectedIndex() != -1 && this.cbdest.getSelectedIndex() != -1 && this.txtSource.getText() != ""){

                fondo = 0.0;                                      

                this.valbase = 0.0;

                try{
                    valbase = Double.parseDouble(this.txtSource.getText());
                }
                catch(Exception ex){
                    if(!ex.toString().contains("empty")){
                        this.msgerr(ex.toString());
                    }
                }
                
                fondo = (valbase / this.tipos.get(this.cborigen.getSelectedIndex()).getdllval())*this.tipos.get(this.cbdest.getSelectedIndex()).getdllval();
                
                this.txtDest.setText("$"+String.format("%.5f",this.fondo));                                                        
            }
    }
    
    private void msgerr(String msg){
        JOptionPane.showMessageDialog(this,msg,"Error",JOptionPane.ERROR_MESSAGE);
    }
    
    private void msgok(String msg){
        JOptionPane.showMessageDialog(this,msg,"Aviso",JOptionPane.OK_OPTION);
    }
    
    private void msgdang(String msg){
        JOptionPane.showMessageDialog(this,msg,"Aviso",JOptionPane.WARNING_MESSAGE);
    }
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cborigen = new javax.swing.JComboBox<>();
        cbdest = new javax.swing.JComboBox<>();
        txtSource = new BASE.JTextFieldDecimal();
        txtDest = new BASE.JTextFieldDecimal();
        btnchange = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cborigen.setBackground(new java.awt.Color(255, 204, 102));
        cborigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cborigen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cborigenItemStateChanged(evt);
            }
        });
        cborigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cborigenMouseClicked(evt);
            }
        });

        cbdest.setBackground(new java.awt.Color(255, 102, 102));
        cbdest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbdest.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbdestItemStateChanged(evt);
            }
        });

        txtSource.setBackground(new java.awt.Color(255, 204, 102));
        txtSource.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSourceKeyReleased(evt);
            }
        });

        txtDest.setEditable(false);
        txtDest.setBackground(new java.awt.Color(255, 102, 102));

        btnchange.setBackground(java.awt.SystemColor.textHighlight);
        btnchange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESOURCES/update.png"))); // NOI18N
        btnchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangeActionPerformed(evt);
            }
        });

        jLabel1.setBackground(java.awt.SystemColor.text);
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel1.setText(">>Rubricas de Consulta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbdest, 0, 148, Short.MAX_VALUE)
                            .addComponent(cborigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSource, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtDest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnchange, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cborigen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnchange, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDest, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbdest, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSourceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSourceKeyReleased
        this.translate();
    }//GEN-LAST:event_txtSourceKeyReleased

    private void cborigenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cborigenItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            this.translate();            
        }
    }//GEN-LAST:event_cborigenItemStateChanged

    private void cborigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cborigenMouseClicked
        
    }//GEN-LAST:event_cborigenMouseClicked

    private void cbdestItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbdestItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            this.translate();            
        }
    }//GEN-LAST:event_cbdestItemStateChanged

    private void btnchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangeActionPerformed
        
        if(this.cborigen.getSelectedIndex() != -1 && this.cbdest.getSelectedIndex() != -1){
            int watch = this.cbdest.getSelectedIndex();

            this.cbdest.setSelectedIndex(this.cborigen.getSelectedIndex());

            this.cborigen.setSelectedIndex(watch);
        }
        else{
            this.msgdang("Seleccione Tipos de Cambio!");
        }
    }//GEN-LAST:event_btnchangeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchange;
    private javax.swing.JComboBox<String> cbdest;
    private javax.swing.JComboBox<String> cborigen;
    private javax.swing.JLabel jLabel1;
    private BASE.JTextFieldDecimal txtDest;
    private BASE.JTextFieldDecimal txtSource;
    // End of variables declaration//GEN-END:variables
}
